### PR TITLE
Fix post icons in Admin UI

### LINKED ISSUE #8: Menu icons aren't always Dashicons
If an icon is registered with `$menu_icon` that's not a Dashicon, it gets printed to the `span` in https://github.com/highrisedigital/better-admin-post-types/blob/master/inc/admin/admin-menu-content.php#L67, which prevents it from displaying properly.

For example, I have a CPT registered with an SVG string which shows up in the Admin UI as expected, but gets injected into the DOM as class name instead of as an image.
If I change to a URL, it's treated as a class name instead of the `src` attribute of an `img` element, as expected.

Since CPTs can be registered with values for `$menu_icon` other than Dashicons, (see https://developer.wordpress.org/reference/functions/register_post_type/#parameters), add conditional checks to determine what's been registered before using it.

### PR DESCRIPTION
**Pull request by morganestes**
Allows post icons that aren't Dashicons to be displayed properly in the Admin UI.

This changes the return value of `bapt_get_content_block_dashicon()` to indicate if a `$menu_icon` is an SVG string or a URL and returns that instead of the Dashicon. In the front end, check for these values and print the correct HTML `img` tags for each, with a fallback to Dashicons as currently used.

Fixes #8

### CODE REVIEW

File: inc/bapt-functions.php [hunk 1]
```diff
@@ -9,14 +9,24 @@
...
  * declared with a dashicon then the default post icon is returend.
  *
- * @param  obj $post_type_obj the post type object to retrieve the icon from.
+ * @param  WP_Post_Type $post_type_obj the post type object to retrieve the icon from.
  * @return string             the class name of the icon to return - defaults to 'dashicons-admin-post'.
  */
 function bapt_get_content_block_dashicon( $post_type_obj ) {
 	if ( null !== $post_type_obj->menu_icon ) {
+
+		if ( strstr( $post_type_obj->menu_icon, 'data:image/svg+xml;' ) ) {
```
Comment (wpmark) [inline inc/bapt-functions.php]: @morganestes could you add some comments here please as to what these if statements are doing

Comment (morganestes) [reply inc/bapt-functions.php]: You bet. I'll update the PR.

**Comment by morganestes** [comment]
@wpmark I switched from `strstr()` to `strpos()` for checking the icon since it's supposed to be a bit faster, and updated the docs inline and in the docblock.
